[project]
name = "iozarrpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Benjamin Sobel", email = "ben-developer@opayq.com" }
]
requires-python = ">=3.13"
dependencies = ["polars>=0.20.0"]

[project.optional-dependencies]
test = [
    "numpy>=1.26",
    "xarray>=2024.10.0",
    "zarr>=3.0.0",
    "numcodecs>=0.13.0",
]

[project.scripts]
iozarrpy = "iozarrpy:main"

[tool.maturin]
module-name = "iozarrpy._core"
python-packages = ["iozarrpy"]
python-source = "src"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/**/*.rs" }, { file = "Cargo.toml" }, { file = "Cargo.lock" }]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
