[project]
name = "rainbear-workspace"
version = "0.1.0"
requires-python = ">=3.13"

[tool.uv.workspace]
members = ["rainbear", "rainbear-tests"]

[tool.uv.sources]
rainbear = { workspace = true }

[dependency-groups]
dev = [
    "rust-just>=1.46.0",
]

